import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUserVerificationFields1770447692911 implements MigrationInterface {
    name = 'AddUserVerificationFields1770447692911'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`article_translations\` DROP FOREIGN KEY \`FK_f6b102769f893b3d2562a4c1c6c\``);
        await queryRunner.query(`ALTER TABLE \`book_translations\` DROP FOREIGN KEY \`FK_711de461c8fcc1a9ff6864142dc\``);
        await queryRunner.query(`ALTER TABLE \`book_translations\` DROP FOREIGN KEY \`FK_805a09bc0444e439b53dfc0b061\``);
        await queryRunner.query(`ALTER TABLE \`user_post_shares\` DROP FOREIGN KEY \`FK_user_post_share_user\``);
        await queryRunner.query(`DROP INDEX \`unique_post_lang\` ON \`scholar_post_translations\``);
        await queryRunner.query(`DROP INDEX \`idx_scholar_posts_scholar_created\` ON \`scholar_posts\``);
        await queryRunner.query(`DROP INDEX \`idx_users_active\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_shared_book_id\` ON \`user_posts\``);
        await queryRunner.query(`DROP INDEX \`idx_user_posts_status_created\` ON \`user_posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_posts_type\` ON \`user_posts\``);
        await queryRunner.query(`DROP INDEX \`idx_user_posts_user_id_status_created\` ON \`user_posts\``);
        await queryRunner.query(`DROP INDEX \`FK_user_post_share_post\` ON \`user_post_shares\``);
        await queryRunner.query(`DROP INDEX \`IDX_user_post_share_unique\` ON \`user_post_shares\``);
        await queryRunner.query(`DROP INDEX \`idx_user_post_comments_post\` ON \`user_post_comments\``);
        await queryRunner.query(`DROP INDEX \`idx_user_post_comments_user\` ON \`user_post_comments\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`author\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`coverImage\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`coverUrl\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`publishDate\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`book_languages\` DROP COLUMN \`pdfUrl\``);
        await queryRunner.query(`ALTER TABLE \`languages\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`languages\` DROP COLUMN \`isActive\``);
        await queryRunner.query(`ALTER TABLE \`languages\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`languages\` ADD \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`languages\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`languages\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`coverUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`coverImage\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`author\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`publishDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`isVerified\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`verificationToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`verificationTokenExpires\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`scholar_post_translations\` DROP COLUMN \`postId\``);
        await queryRunner.query(`ALTER TABLE \`scholar_post_translations\` ADD \`postId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`scholars\` DROP COLUMN \`biography\``);
        await queryRunner.query(`ALTER TABLE \`scholars\` ADD \`biography\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`articles\` DROP COLUMN \`coverImage\``);
        await queryRunner.query(`ALTER TABLE \`articles\` ADD \`coverImage\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`articles\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`articles\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`articles\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`articles\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`article_translations\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`article_translations\` ADD \`slug\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`article_translations\` DROP COLUMN \`pdfUrl\``);
        await queryRunner.query(`ALTER TABLE \`article_translations\` ADD \`pdfUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`book_translations\` CHANGE \`languageId\` \`languageId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`book_languages\` CHANGE \`languageId\` \`languageId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`book_languages\` CHANGE \`bookId\` \`bookId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`biography\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`biography\` varchar(300) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`phoneNo\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`phoneNo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_posts\` CHANGE \`status\` \`status\` enum ('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`user_post_shares\` DROP COLUMN \`post_id\``);
        await queryRunner.query(`ALTER TABLE \`user_post_shares\` ADD \`post_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_post_shares\` CHANGE \`post_type\` \`post_type\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`podcasts\` CHANGE \`isActive\` \`isActive\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`podcasts\` CHANGE \`isFeatured\` \`isFeatured\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`podcasts\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`podcasts\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`podcasts\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`podcasts\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`book_translations\` CHANGE \`languageId\` \`languageId\` int NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_35efad6238b50c07ad5b20b827\` ON \`user_post_shares\` (\`user_id\`, \`post_id\`)`);
        await queryRunner.query(`ALTER TABLE \`scholar_post_translations\` ADD CONSTRAINT \`FK_2f41c5bab197e79cbefa0ada105\` FOREIGN KEY (\`postId\`) REFERENCES \`scholar_posts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`article_translations\` ADD CONSTRAINT \`FK_f6b102769f893b3d2562a4c1c6c\` FOREIGN KEY (\`languageId\`) REFERENCES \`languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book_translations\` ADD CONSTRAINT \`FK_4cfdbee090831904e931ca13a41\` FOREIGN KEY (\`bookId\`) REFERENCES \`books\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book_translations\` ADD CONSTRAINT \`FK_46a120cd82834485344bc515a05\` FOREIGN KEY (\`languageId\`) REFERENCES \`languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book_languages\` ADD CONSTRAINT \`FK_805a09bc0444e439b53dfc0b061\` FOREIGN KEY (\`languageId\`) REFERENCES \`languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book_languages\` ADD CONSTRAINT \`FK_711de461c8fcc1a9ff6864142dc\` FOREIGN KEY (\`bookId\`) REFERENCES \`books\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_posts\` ADD CONSTRAINT \`FK_441391a3d99f2320003357c8626\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_post_shares\` ADD CONSTRAINT \`FK_935d0c4a50497c07278e54fb1a3\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_post_shares\` ADD CONSTRAINT \`FK_ebb18b529c9f3a65e6995dd5203\` FOREIGN KEY (\`post_id\`) REFERENCES \`user_posts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_post_shares\` DROP FOREIGN KEY \`FK_ebb18b529c9f3a65e6995dd5203\``);
        await queryRunner.query(`ALTER TABLE \`user_post_shares\` DROP FOREIGN KEY \`FK_935d0c4a50497c07278e54fb1a3\``);
        await queryRunner.query(`ALTER TABLE \`user_posts\` DROP FOREIGN KEY \`FK_441391a3d99f2320003357c8626\``);
        await queryRunner.query(`ALTER TABLE \`book_languages\` DROP FOREIGN KEY \`FK_711de461c8fcc1a9ff6864142dc\``);
        await queryRunner.query(`ALTER TABLE \`book_languages\` DROP FOREIGN KEY \`FK_805a09bc0444e439b53dfc0b061\``);
        await queryRunner.query(`ALTER TABLE \`book_translations\` DROP FOREIGN KEY \`FK_46a120cd82834485344bc515a05\``);
        await queryRunner.query(`ALTER TABLE \`book_translations\` DROP FOREIGN KEY \`FK_4cfdbee090831904e931ca13a41\``);
        await queryRunner.query(`ALTER TABLE \`article_translations\` DROP FOREIGN KEY \`FK_f6b102769f893b3d2562a4c1c6c\``);
        await queryRunner.query(`ALTER TABLE \`scholar_post_translations\` DROP FOREIGN KEY \`FK_2f41c5bab197e79cbefa0ada105\``);
        await queryRunner.query(`DROP INDEX \`IDX_35efad6238b50c07ad5b20b827\` ON \`user_post_shares\``);
        await queryRunner.query(`ALTER TABLE \`book_translations\` CHANGE \`languageId\` \`languageId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`podcasts\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`podcasts\` ADD \`updatedAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`podcasts\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`podcasts\` ADD \`createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`podcasts\` CHANGE \`isFeatured\` \`isFeatured\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`podcasts\` CHANGE \`isActive\` \`isActive\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`user_post_shares\` CHANGE \`post_type\` \`post_type\` varchar(50) COLLATE "utf8mb4_general_ci" NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE \`user_post_shares\` DROP COLUMN \`post_id\``);
        await queryRunner.query(`ALTER TABLE \`user_post_shares\` ADD \`post_id\` varchar(255) COLLATE "utf8mb4_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_posts\` CHANGE \`status\` \`status\` enum COLLATE "utf8mb4_general_ci" ('pending', 'approved', 'rejected') NOT NULL DEFAULT 'approved'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`phoneNo\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`phoneNo\` varchar(50) COLLATE "utf8mb4_general_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`biography\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`biography\` varchar(255) COLLATE "utf8mb4_general_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`book_languages\` CHANGE \`bookId\` \`bookId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`book_languages\` CHANGE \`languageId\` \`languageId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`book_translations\` CHANGE \`languageId\` \`languageId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`article_translations\` DROP COLUMN \`pdfUrl\``);
        await queryRunner.query(`ALTER TABLE \`article_translations\` ADD \`pdfUrl\` varchar(500) COLLATE "utf8mb4_general_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`article_translations\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`article_translations\` ADD \`slug\` varchar(500) COLLATE "utf8mb4_general_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`articles\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`articles\` ADD \`updatedAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`articles\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`articles\` ADD \`createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`articles\` DROP COLUMN \`coverImage\``);
        await queryRunner.query(`ALTER TABLE \`articles\` ADD \`coverImage\` varchar(500) COLLATE "utf8mb4_general_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`scholars\` DROP COLUMN \`biography\``);
        await queryRunner.query(`ALTER TABLE \`scholars\` ADD \`biography\` longtext COLLATE "utf8mb4_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`scholar_post_translations\` DROP COLUMN \`postId\``);
        await queryRunner.query(`ALTER TABLE \`scholar_post_translations\` ADD \`postId\` varchar(36) COLLATE "utf8mb4_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`verificationTokenExpires\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`verificationToken\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`isVerified\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`publishDate\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`author\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`coverImage\``);
        await queryRunner.query(`ALTER TABLE \`books\` DROP COLUMN \`coverUrl\``);
        await queryRunner.query(`ALTER TABLE \`languages\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`languages\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`languages\` DROP COLUMN \`isActive\``);
        await queryRunner.query(`ALTER TABLE \`languages\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`languages\` ADD \`isActive\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`languages\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`book_languages\` ADD \`pdfUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`publishDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`coverUrl\` varchar(255) COLLATE "utf8mb4_general_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`coverImage\` varchar(255) COLLATE "utf8mb4_general_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`books\` ADD \`author\` varchar(255) COLLATE "utf8mb4_general_ci" NULL`);
        await queryRunner.query(`CREATE INDEX \`idx_user_post_comments_user\` ON \`user_post_comments\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_post_comments_post\` ON \`user_post_comments\` (\`post_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_user_post_share_unique\` ON \`user_post_shares\` (\`user_id\`, \`post_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_user_post_share_post\` ON \`user_post_shares\` (\`post_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_posts_user_id_status_created\` ON \`user_posts\` (\`user_id\`, \`created_at\`, \`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_user_posts_type\` ON \`user_posts\` (\`type\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_user_posts_status_created\` ON \`user_posts\` (\`created_at\`, \`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_shared_book_id\` ON \`user_posts\` (\`shared_book_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_users_active\` ON \`users\` (\`id\`, \`isActive\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_scholar_posts_scholar_created\` ON \`scholar_posts\` (\`scholarId\`, \`createdAt\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`unique_post_lang\` ON \`scholar_post_translations\` (\`postId\`, \`language\`)`);
        await queryRunner.query(`ALTER TABLE \`user_post_shares\` ADD CONSTRAINT \`FK_user_post_share_user\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book_translations\` ADD CONSTRAINT \`FK_805a09bc0444e439b53dfc0b061\` FOREIGN KEY (\`languageId\`) REFERENCES \`languages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book_translations\` ADD CONSTRAINT \`FK_711de461c8fcc1a9ff6864142dc\` FOREIGN KEY (\`bookId\`) REFERENCES \`books\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`article_translations\` ADD CONSTRAINT \`FK_f6b102769f893b3d2562a4c1c6c\` FOREIGN KEY (\`languageId\`) REFERENCES \`languages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
