server {
    listen 80;
    server_name islamicwindows.org www.islamicwindows.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://islamicwindows.com$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name islamicwindows.org www.islamicwindows.org;

    ssl_certificate /etc/letsencrypt/live/islamicwindows.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/islamicwindows.org/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    return 301 https://islamicwindows.com$request_uri;
}
