/**
 * Ethnologue top-300 listesinden sisteme eklenen diller.
 * Her dil: ISO kodu, Türkçe ad, bayrak ülkesi, ilişkili ülkeler (alpha2).
 * Kaynak: Dunyada_En_Cok_Kullanilan_300_Dil_Ethnologue_Incelemeli.pdf
 */

export interface EthnologueLanguageSeed {
  code: string;
  name: string;
  flagCountry: string;
  countries: string[];
  rank: number;
}

export const ETHNOLOGUE300_LANGUAGES: EthnologueLanguageSeed[] = [
  { rank: 10, code: 'pa', name: 'Pencapça', flagCountry: 'pk', countries: ['PK', 'IN'] },
  { rank: 30, code: 'bho', name: 'Bhojpuri', flagCountry: 'in', countries: ['IN', 'NP'] },
  { rank: 36, code: 'su', name: 'Sundaca', flagCountry: 'id', countries: ['ID'] },
  { rank: 40, code: 'om', name: 'Oromo', flagCountry: 'et', countries: ['ET', 'KE'] },
  { rank: 43, code: 'mai', name: 'Maithili', flagCountry: 'in', countries: ['IN', 'NP'] },
  { rank: 48, code: 'sd', name: 'Sindhi', flagCountry: 'pk', countries: ['PK', 'IN'] },
  { rank: 49, code: 'pcm', name: 'Nijerya Pidgin', flagCountry: 'ng', countries: ['NG'] },
  { rank: 52, code: 'skr', name: 'Saraiki', flagCountry: 'pk', countries: ['PK'] },
  { rank: 59, code: 'ceb', name: 'Sebuano', flagCountry: 'ph', countries: ['PH'] },
  { rank: 67, code: 'hne', name: 'Chhattisgarhi', flagCountry: 'in', countries: ['IN'] },
  { rank: 68, code: 'raj', name: 'Rajasthani', flagCountry: 'in', countries: ['IN'] },
  { rank: 70, code: 'dyu', name: 'Dyula', flagCountry: 'ci', countries: ['CI', 'ML', 'BF'] },
  { rank: 74, code: 'zha', name: 'Zhuangca', flagCountry: 'cn', countries: ['CN'] },
  { rank: 75, code: 'as', name: 'Assamca', flagCountry: 'in', countries: ['IN'] },
  { rank: 76, code: 'ctg', name: 'Chittagonian', flagCountry: 'bd', countries: ['BD'] },
  { rank: 80, code: 'rkt', name: 'Rangpuri', flagCountry: 'bd', countries: ['BD', 'IN'] },
  { rank: 83, code: 'nso', name: 'Pedi', flagCountry: 'za', countries: ['ZA'] },
  { rank: 84, code: 'st', name: 'Güney Sotho', flagCountry: 'ls', countries: ['LS', 'ZA'] },
  { rank: 85, code: 'ak', name: 'Akan', flagCountry: 'gh', countries: ['GH'] },
  { rank: 86, code: 'dcc', name: 'Deccan', flagCountry: 'in', countries: ['IN'] },
  { rank: 87, code: 'bgc', name: 'Haryanvi', flagCountry: 'in', countries: ['IN'] },
  { rank: 89, code: 'mag', name: 'Magahi', flagCountry: 'in', countries: ['IN'] },
  { rank: 92, code: 'ts', name: 'Tsonga', flagCountry: 'za', countries: ['ZA', 'MZ'] },
  { rank: 93, code: 'dag', name: 'Dagbani', flagCountry: 'gh', countries: ['GH'] },
  { rank: 94, code: 'ht', name: 'Haiti Kreolcesi', flagCountry: 'ht', countries: ['HT'] },
  { rank: 95, code: 'ny', name: 'Nyanja', flagCountry: 'mw', countries: ['MW', 'ZM'] },
  { rank: 104, code: 'dhd', name: 'Dhundari', flagCountry: 'in', countries: ['IN'] },
  { rank: 105, code: 'bjj', name: 'Kanauji', flagCountry: 'in', countries: ['IN'] },
  { rank: 106, code: 'vmf', name: 'Mainfränkisch', flagCountry: 'de', countries: ['DE'] },
  { rank: 111, code: 'syl', name: 'Sylheti', flagCountry: 'bd', countries: ['BD'] },
  { rank: 116, code: 'ilo', name: 'Ilocano', flagCountry: 'ph', countries: ['PH'] },
  { rank: 117, code: 'kln', name: 'Kalenjin', flagCountry: 'ke', countries: ['KE'] },
  { rank: 118, code: 'ymm', name: 'Maay', flagCountry: 'so', countries: ['SO'] },
  { rank: 119, code: 'qu', name: 'Keçuaca', flagCountry: 'pe', countries: ['PE', 'BO', 'EC'] },
  { rank: 122, code: 'bfy', name: 'Bagheli', flagCountry: 'in', countries: ['IN'] },
  { rank: 123, code: 'bal', name: 'Beluçça', flagCountry: 'pk', countries: ['PK', 'IR'] },
  { rank: 124, code: 'kr', name: 'Kanuri', flagCountry: 'ne', countries: ['NE', 'TD', 'NG'] },
  { rank: 126, code: 'mwr', name: 'Marwari', flagCountry: 'in', countries: ['IN'] },
  { rank: 129, code: 'suk', name: 'Sukuma', flagCountry: 'tz', countries: ['TZ'] },
  { rank: 131, code: 'tn', name: 'Tswana', flagCountry: 'bw', countries: ['BW', 'ZA'] },
  { rank: 132, code: 'af', name: 'Afrikaans', flagCountry: 'za', countries: ['ZA'] },
  { rank: 133, code: 'bjn', name: 'Banjarca', flagCountry: 'id', countries: ['ID'] },
  { rank: 136, code: 'hil', name: 'Hiligaynon', flagCountry: 'ph', countries: ['PH'] },
  { rank: 137, code: 'ks', name: 'Keşmirce', flagCountry: 'in', countries: ['IN'] },
  { rank: 138, code: 'ki', name: 'Kikuyu', flagCountry: 'ke', countries: ['KE'] },
  { rank: 139, code: 'mad', name: 'Madurese', flagCountry: 'id', countries: ['ID'] },
  { rank: 140, code: 'vmw', name: 'Makhuwa', flagCountry: 'mz', countries: ['MZ'] },
  { rank: 141, code: 'mgh', name: 'Makhuwa-Meetto', flagCountry: 'mz', countries: ['MZ'] },
  { rank: 142, code: 'mos', name: 'Mossi', flagCountry: 'bf', countries: ['BF'] },
  { rank: 143, code: 'sat', name: 'Santali', flagCountry: 'in', countries: ['IN'] },
  { rank: 145, code: 'umb', name: 'Umbundu', flagCountry: 'ao', countries: ['AO'] },
  { rank: 146, code: 'vah', name: 'Varhadi-Nagpuri', flagCountry: 'in', countries: ['IN'] },
  { rank: 147, code: 'wal', name: 'Wolaytta', flagCountry: 'et', countries: ['ET'] },
  { rank: 149, code: 'hye', name: 'Armenian', flagCountry: 'un', countries: [] },
  { rank: 150, code: 'kab', name: 'Kabyle', flagCountry: 'dz', countries: ['DZ'] },
  { rank: 152, code: 'lmn', name: 'Lambadi', flagCountry: 'in', countries: ['IN'] },
  { rank: 153, code: 'lua', name: 'Luba-Lulua', flagCountry: 'cd', countries: ['CD'] },
  { rank: 154, code: 'mzn', name: 'Mazanderani', flagCountry: 'ir', countries: ['IR'] },
  { rank: 155, code: 'min', name: 'Minangkabau', flagCountry: 'id', countries: ['ID'] },
  { rank: 156, code: 'nap', name: 'Neapolitan', flagCountry: 'it', countries: ['IT'] },
  { rank: 160, code: 'bug', name: 'Buginese', flagCountry: 'id', countries: ['ID'] },
  { rank: 161, code: 'dan', name: 'Danish', flagCountry: 'un', countries: [] },
  { rank: 162, code: 'fin', name: 'Finnish', flagCountry: 'un', countries: [] },
  { rank: 163, code: 'gpe', name: 'Gana Pidgin İngilizcesi', flagCountry: 'gh', countries: ['GH'] },
  { rank: 164, code: 'gn', name: 'Guarani', flagCountry: 'py', countries: ['PY', 'BO'] },
  { rank: 165, code: 'hoj', name: 'Hadothi', flagCountry: 'in', countries: ['IN'] },
  { rank: 170, code: 'mak', name: 'Makasar', flagCountry: 'id', countries: ['ID'] },
  { rank: 171, code: 'mup', name: 'Malvi', flagCountry: 'in', countries: ['IN'] },
  { rank: 172, code: 'mtr', name: 'Mewari', flagCountry: 'in', countries: ['IN'] },
  { rank: 176, code: 'gsw', name: 'İsviçre Almancası', flagCountry: 'ch', countries: ['CH', 'LI'] },
  { rank: 177, code: 'shi', name: 'Tachelhit', flagCountry: 'ma', countries: ['MA'] },
  { rank: 178, code: 'tiv', name: 'Tiv', flagCountry: 'ng', countries: ['NG'] },
  { rank: 179, code: 'ace', name: 'Acehce', flagCountry: 'id', countries: ['ID'] },
  { rank: 180, code: 'awa', name: 'Awadhi', flagCountry: 'in', countries: ['IN', 'NP'] },
  { rank: 181, code: 'bxg', name: 'Bangala', flagCountry: 'cd', countries: ['CD'] },
  { rank: 182, code: 'bci', name: 'Baoulé', flagCountry: 'ci', countries: ['CI'] },
  { rank: 183, code: 'bem', name: 'Bemba (Zambia)', flagCountry: 'un', countries: [] },
  { rank: 184, code: 'cat', name: 'Catalan', flagCountry: 'un', countries: [] },
  { rank: 185, code: 'hrv', name: 'Croatian', flagCountry: 'un', countries: [] },
  { rank: 186, code: 'ewe', name: 'Ewe', flagCountry: 'un', countries: [] },
  { rank: 187, code: 'lug', name: 'Ganda', flagCountry: 'un', countries: [] },
  { rank: 188, code: 'kat', name: 'Georgian', flagCountry: 'un', countries: [] },
  { rank: 189, code: 'heb', name: 'Modern Hebrew', flagCountry: 'un', countries: [] },
  { rank: 190, code: 'kam', name: 'Kamba (Kenya)', flagCountry: 'un', countries: [] },
  { rank: 191, code: 'kmb', name: 'Kimbundu', flagCountry: 'ao', countries: ['AO'] },
  { rank: 192, code: 'kok', name: 'Konkani (macrolanguage)', flagCountry: 'un', countries: [] },
  { rank: 193, code: 'kri', name: 'Krio', flagCountry: 'sl', countries: ['SL'] },
  { rank: 194, code: 'lmo', name: 'Lombard', flagCountry: 'it', countries: ['IT'] },
  { rank: 195, code: 'luo', name: 'Luo', flagCountry: 'ke', countries: ['KE'] },
  { rank: 196, code: 'vmk', name: 'Makhuwa-Shirima', flagCountry: 'un', countries: [] },
  { rank: 197, code: 'hno', name: 'Northern Hindko', flagCountry: 'un', countries: [] },
  { rank: 198, code: 'rom', name: 'Romany', flagCountry: 'un', countries: [] },
  { rank: 199, code: 'sck', name: 'Sadri', flagCountry: 'un', countries: [] },
  { rank: 200, code: 'shn', name: 'Shan', flagCountry: 'un', countries: [] },
  { rank: 201, code: 'scn', name: 'Sicilyaca', flagCountry: 'it', countries: ['IT'] },
  { rank: 202, code: 'sid', name: 'Sidamo', flagCountry: 'et', countries: ['ET'] },
  { rank: 203, code: 'sou', name: 'Southern Thai', flagCountry: 'un', countries: [] },
  { rank: 204, code: 'tke', name: 'Takwane', flagCountry: 'mz', countries: ['MZ'] },
  { rank: 205, code: 'tat', name: 'Tatar', flagCountry: 'un', countries: [] },
  { rank: 206, code: 'tpi', name: 'Tok Pisin', flagCountry: 'pg', countries: ['PG'] },
  { rank: 207, code: 'vec', name: 'Venedikçe', flagCountry: 'it', countries: ['IT'] },
  { rank: 208, code: 'wo', name: 'Wolof', flagCountry: 'sn', countries: ['SN', 'GM', 'MR'] },
  { rank: 209, code: 'dje', name: 'Zarma', flagCountry: 'ne', countries: ['NE'] },
  { rank: 210, code: 'ay', name: 'Aymara', flagCountry: 'bo', countries: ['BO', 'PE'] },
  { rank: 211, code: 'ban', name: 'Balinese', flagCountry: 'id', countries: ['ID'] },
  { rank: 212, code: 'bhb', name: 'Bhili', flagCountry: 'in', countries: ['IN'] },
  { rank: 213, code: 'pcc', name: 'Bouyei', flagCountry: 'cn', countries: ['CN'] },
  { rank: 214, code: 'brh', name: 'Brahui', flagCountry: 'pk', countries: ['PK'] },
  { rank: 215, code: 'bns', name: 'Bundeli', flagCountry: 'in', countries: ['IN'] },
  { rank: 216, code: 'sef', name: 'Cebaara Senoufo', flagCountry: 'ci', countries: ['CI'] },
  { rank: 217, code: 'egl', name: 'Emilian', flagCountry: 'it', countries: ['IT'] },
  { rank: 218, code: 'gbm', name: 'Garhwali', flagCountry: 'in', countries: ['IN'] },
  { rank: 219, code: 'gdx', name: 'Godwari', flagCountry: 'in', countries: ['IN'] },
  { rank: 220, code: 'gon', name: 'Gondi', flagCountry: 'in', countries: ['IN'] },
  { rank: 221, code: 'mey', name: 'Hassaniyya', flagCountry: 'mr', countries: ['MR'] },
  { rank: 222, code: 'haz', name: 'Hazaragi', flagCountry: 'af', countries: ['AF'] },
  { rank: 223, code: 'hmn', name: 'Hmong', flagCountry: 'cn', countries: ['CN', 'LA', 'VN'] },
  { rank: 224, code: 'hrx', name: 'Hunsrik', flagCountry: 'br', countries: ['BR'] },
  { rank: 225, code: 'jam', name: 'Jamaika Kreol İngilizcesi', flagCountry: 'jm', countries: ['JM'] },
  { rank: 226, code: 'meo', name: 'Kedah Malay', flagCountry: 'un', countries: [] },
  { rank: 227, code: 'lit', name: 'Lithuanian', flagCountry: 'un', countries: [] },
  { rank: 228, code: 'myx', name: 'Masaaba', flagCountry: 'un', countries: [] },
  { rank: 229, code: 'men', name: 'Mende', flagCountry: 'sl', countries: ['SL'] },
  { rank: 230, code: 'wtm', name: 'Mewati', flagCountry: 'un', countries: [] },
  { rank: 231, code: 'mui', name: 'Musi', flagCountry: 'un', countries: [] },
  { rank: 232, code: 'gno', name: 'Northern Gondi', flagCountry: 'un', countries: [] },
  { rank: 233, code: 'nyn', name: 'Nyankole', flagCountry: 'un', countries: [] },
  { rank: 234, code: 'cpx', name: 'Pu-Xian Chinese', flagCountry: 'un', countries: [] },
  { rank: 235, code: 'ksw', name: 'S\'gaw Karen', flagCountry: 'un', countries: [] },
  { rank: 236, code: 'msi', name: 'Sabah Malay', flagCountry: 'un', countries: [] },
  { rank: 237, code: 'swv', name: 'Shekhawati', flagCountry: 'un', countries: [] },
  { rank: 238, code: 'xog', name: 'Soga', flagCountry: 'un', countries: [] },
  { rank: 239, code: 'quh', name: 'South Bolivian Quechua', flagCountry: 'un', countries: [] },
  { rank: 240, code: 'sdh', name: 'Southern Kurdish', flagCountry: 'un', countries: [] },
  { rank: 241, code: 'ssw', name: 'Swazi', flagCountry: 'un', countries: [] },
  { rank: 242, code: 'tyz', name: 'Tày', flagCountry: 'un', countries: [] },
  { rank: 243, code: 'wbr', name: 'Wagdi', flagCountry: 'un', countries: [] },
  { rank: 244, code: 'war', name: 'Waray (Philippines)', flagCountry: 'un', countries: [] },
  { rank: 245, code: 'yao', name: 'Yao', flagCountry: 'un', countries: [] },
  { rank: 246, code: 'zza', name: 'Zaza', flagCountry: 'un', countries: [] },
  { rank: 247, code: 'aar', name: 'Afar', flagCountry: 'un', countries: [] },
  { rank: 248, code: 'alz', name: 'Alur', flagCountry: 'un', countries: [] },
  { rank: 249, code: 'abs', name: 'Ambonese Malay', flagCountry: 'un', countries: [] },
  { rank: 250, code: 'anw', name: 'Anaang', flagCountry: 'un', countries: [] },
  { rank: 251, code: 'bgq', name: 'Bagri', flagCountry: 'in', countries: ['IN'] },
  { rank: 252, code: 'bbc', name: 'Batak Toba', flagCountry: 'id', countries: ['ID'] },
  { rank: 253, code: 'bik', name: 'Bikol', flagCountry: 'ph', countries: ['PH'] },
  { rank: 254, code: 'bin', name: 'Bini', flagCountry: 'ng', countries: ['NG'] },
  { rank: 255, code: 'bra', name: 'Braj', flagCountry: 'in', countries: ['IN'] },
  { rank: 256, code: 'wes', name: 'Kamerun Pidgin', flagCountry: 'cm', countries: ['CM'] },
  { rank: 257, code: 'tzm', name: 'Central Atlas Tamazight', flagCountry: 'ma', countries: ['MA'] },
  { rank: 258, code: 'bcl', name: 'Central Bikol', flagCountry: 'ph', countries: ['PH'] },
  { rank: 260, code: 'ryu', name: 'Central Okinawan', flagCountry: 'jp', countries: ['JP'] },
  { rank: 262, code: 'cgg', name: 'Chiga', flagCountry: 'ug', countries: ['UG'] },
  { rank: 263, code: 'dnj', name: 'Dan', flagCountry: 'ci', countries: ['CI'] },
  { rank: 264, code: 'thl', name: 'Dangaura Tharu', flagCountry: 'np', countries: ['NP'] },
  { rank: 265, code: 'doi', name: 'Dogri', flagCountry: 'in', countries: ['IN'] },
  { rank: 267, code: 'igb', name: 'Ebira', flagCountry: 'ng', countries: ['NG'] },
  { rank: 268, code: 'efi', name: 'Efik', flagCountry: 'ng', countries: ['NG'] },
  { rank: 270, code: 'gl', name: 'Galiçyaca', flagCountry: 'es', countries: ['ES'] },
  { rank: 271, code: 'gmv', name: 'Gamo', flagCountry: 'et', countries: ['ET'] },
  { rank: 273, code: 'nyf', name: 'Giryama', flagCountry: 'ke', countries: ['KE'] },
  { rank: 274, code: 'gom', name: 'Goan Konkani', flagCountry: 'in', countries: ['IN'] },
  { rank: 275, code: 'guz', name: 'Gusii', flagCountry: 'ke', countries: ['KE'] },
  { rank: 276, code: 'mww', name: 'Hmong Daw', flagCountry: 'un', countries: [] },
  { rank: 277, code: 'iba', name: 'Iban', flagCountry: 'un', countries: [] },
  { rank: 278, code: 'ibb', name: 'Ibibio', flagCountry: 'un', countries: [] },
  { rank: 279, code: 'ijc', name: 'Izon', flagCountry: 'un', countries: [] },
  { rank: 280, code: 'quc', name: 'K\'iche\'', flagCountry: 'un', countries: [] },
  { rank: 281, code: 'kbd', name: 'Kabardian', flagCountry: 'ru', countries: ['RU'] },
  { rank: 282, code: 'xnr', name: 'Kangri', flagCountry: 'in', countries: ['IN'] },
  { rank: 283, code: 'khn', name: 'Khandesi', flagCountry: 'in', countries: ['IN'] },
  { rank: 284, code: 'sgc', name: 'Kipsigis', flagCountry: 'ke', countries: ['KE'] },
  { rank: 285, code: 'kfy', name: 'Kumaoni', flagCountry: 'in', countries: ['IN'] },
  { rank: 286, code: 'kru', name: 'Kurukh', flagCountry: 'in', countries: ['IN'] },
  { rank: 287, code: 'abl', name: 'Lampung Nyo', flagCountry: 'id', countries: ['ID'] },
  { rank: 288, code: 'laj', name: 'Lango', flagCountry: 'ug', countries: ['UG'] },
  { rank: 289, code: 'lir', name: 'Liberian English', flagCountry: 'lr', countries: ['LR'] },
  { rank: 290, code: 'lis', name: 'Lisu', flagCountry: 'cn', countries: ['CN'] },
  { rank: 291, code: 'ngl', name: 'Lomwe', flagCountry: 'mz', countries: ['MZ'] },
  { rank: 292, code: 'lu', name: 'Luba-Katanga', flagCountry: 'cd', countries: ['CD'] },
  { rank: 293, code: 'lgg', name: 'Lugbara', flagCountry: 'ug', countries: ['UG'] },
  { rank: 295, code: 'lon', name: 'Malawi Lomwe', flagCountry: 'mw', countries: ['MW'] },
  { rank: 296, code: 'mjl', name: 'Mandeali', flagCountry: 'in', countries: ['IN'] },
  { rank: 297, code: 'mni', name: 'Meitei (Manipuri)', flagCountry: 'in', countries: ['IN'] },
  { rank: 298, code: 'mer', name: 'Meru', flagCountry: 'ke', countries: ['KE'] },
  { rank: 299, code: 'unr', name: 'Mundari', flagCountry: 'in', countries: ['IN'] },
  { rank: 300, code: 'ndc', name: 'Ndau', flagCountry: 'mz', countries: ['MZ'] },
];
