export interface Qa300LanguageEntry {
  rank: number;
  englishName: string;
  iso639_3: string;
  nativeName: string;
  direction: 'ltr' | 'rtl';
  aliases: string[];
  parentIso?: string;
  estimatedSpeakers: string;
}

const RTL_CODES = new Set([
  'ara', 'fas', 'urd', 'heb', 'arq', 'afb', 'acw', 'apd', 'aec', 'acm',
  'ayp', 'aeb', 'ayl', 'acq', 'apc', 'shu', 'mey', 'ckb', 'sdh', 'kas',
  'bal', 'bgp', 'mzn', 'glk', 'pus', 'snd', 'skr', 'uig',
]);

export const QA_300_LANGUAGES: Qa300LanguageEntry[] = [
  { rank: 1, englishName: 'Mandarin Chinese', iso639_3: 'cmn', nativeName: '普通话', direction: 'ltr', aliases: ['Mandarin', 'Putonghua', '国语'], parentIso: 'zho', estimatedSpeakers: '920M' },
  { rank: 2, englishName: 'Spanish', iso639_3: 'spa', nativeName: 'Español', direction: 'ltr', aliases: ['Castellano', 'Espanol'], estimatedSpeakers: '490M' },
  { rank: 3, englishName: 'English', iso639_3: 'eng', nativeName: 'English', direction: 'ltr', aliases: ['Inglés', 'İngilizce'], estimatedSpeakers: '373M' },
  { rank: 4, englishName: 'Arabic', iso639_3: 'ara', nativeName: 'العربية', direction: 'rtl', aliases: ['Arabi', 'Arapça', 'عربي'], estimatedSpeakers: '360M' },
  { rank: 5, englishName: 'Hindi', iso639_3: 'hin', nativeName: 'हिन्दी', direction: 'ltr', aliases: ['Hindice', 'Hindī'], estimatedSpeakers: '320M' },
  { rank: 6, englishName: 'Bengali', iso639_3: 'ben', nativeName: 'বাংলা', direction: 'ltr', aliases: ['Bangla', 'Bengalce'], estimatedSpeakers: '240M' },
  { rank: 7, englishName: 'Portuguese', iso639_3: 'por', nativeName: 'Português', direction: 'ltr', aliases: ['Portekizce'], estimatedSpeakers: '230M' },
  { rank: 8, englishName: 'Russian', iso639_3: 'rus', nativeName: 'Русский', direction: 'ltr', aliases: ['Rusça', 'Russkiy'], estimatedSpeakers: '150M' },
  { rank: 9, englishName: 'Japanese', iso639_3: 'jpn', nativeName: '日本語', direction: 'ltr', aliases: ['Japonca', 'Nihongo'], estimatedSpeakers: '128M' },
  { rank: 10, englishName: 'Punjabi', iso639_3: 'pan', nativeName: 'ਪੰਜਾਬੀ', direction: 'ltr', aliases: ['Panjabi', 'Pencapça'], estimatedSpeakers: '113M' },
  { rank: 11, englishName: 'German', iso639_3: 'deu', nativeName: 'Deutsch', direction: 'ltr', aliases: ['Almanca', 'German'], estimatedSpeakers: '95M' },
  { rank: 12, englishName: 'Yue Chinese', iso639_3: 'yue', nativeName: '粵語', direction: 'ltr', aliases: ['Cantonese', 'Kantonca'], parentIso: 'zho', estimatedSpeakers: '86M' },
  { rank: 13, englishName: 'Marathi', iso639_3: 'mar', nativeName: 'मराठी', direction: 'ltr', aliases: ['Marathice'], estimatedSpeakers: '83M' },
  { rank: 14, englishName: 'Javanese', iso639_3: 'jav', nativeName: 'ꦧꦱꦗꦮ', direction: 'ltr', aliases: ['Javaca', 'Basa Jawa'], estimatedSpeakers: '82M' },
  { rank: 15, englishName: 'Turkish', iso639_3: 'tur', nativeName: 'Türkçe', direction: 'ltr', aliases: ['Turkisch', 'Turk', 'Turkce'], estimatedSpeakers: '82M' },
  { rank: 16, englishName: 'Persian', iso639_3: 'fas', nativeName: 'فارسی', direction: 'rtl', aliases: ['Farsi', 'Farsça', 'فارسي'], estimatedSpeakers: '81M' },
  { rank: 17, englishName: 'Telugu', iso639_3: 'tel', nativeName: 'తెలుగు', direction: 'ltr', aliases: ['Teluguca'], estimatedSpeakers: '81M' },
  { rank: 18, englishName: 'French', iso639_3: 'fra', nativeName: 'Français', direction: 'ltr', aliases: ['Fransızca', 'Francais'], estimatedSpeakers: '80M' },
  { rank: 19, englishName: 'Korean', iso639_3: 'kor', nativeName: '한국어', direction: 'ltr', aliases: ['Korece', 'Hangugeo'], estimatedSpeakers: '80M' },
  { rank: 20, englishName: 'Wu Chinese', iso639_3: 'wuu', nativeName: '吴语', direction: 'ltr', aliases: ['Shanghainese'], parentIso: 'zho', estimatedSpeakers: '80M' },
  { rank: 21, englishName: 'Tamil', iso639_3: 'tam', nativeName: 'தமிழ்', direction: 'ltr', aliases: ['Tamilce'], estimatedSpeakers: '78M' },
  { rank: 22, englishName: 'Malay', iso639_3: 'msa', nativeName: 'Bahasa Melayu', direction: 'ltr', aliases: ['Malezya Dili', 'Malayca'], estimatedSpeakers: '77M' },
  { rank: 23, englishName: 'Vietnamese', iso639_3: 'vie', nativeName: 'Tiếng Việt', direction: 'ltr', aliases: ['Vietnamca'], estimatedSpeakers: '76M' },
  { rank: 24, englishName: 'Thai', iso639_3: 'tha', nativeName: 'ภาษาไทย', direction: 'ltr', aliases: ['Tayca', 'Siamese'], estimatedSpeakers: '70M' },
  { rank: 25, englishName: 'Urdu', iso639_3: 'urd', nativeName: 'اردو', direction: 'rtl', aliases: ['Urduca', 'اُردُو'], estimatedSpeakers: '70M' },
  { rank: 26, englishName: 'Italian', iso639_3: 'ita', nativeName: 'Italiano', direction: 'ltr', aliases: ['İtalyanca'], estimatedSpeakers: '65M' },
  { rank: 27, englishName: 'Jinyu Chinese', iso639_3: 'cjy', nativeName: '晋语', direction: 'ltr', aliases: ['Jin Chinese'], parentIso: 'zho', estimatedSpeakers: '63M' },
  { rank: 28, englishName: 'Igbo', iso639_3: 'ibo', nativeName: 'Igbo', direction: 'ltr', aliases: ['Ibo'], estimatedSpeakers: '60M' },
  { rank: 29, englishName: 'Gujarati', iso639_3: 'guj', nativeName: 'ગુજરાતી', direction: 'ltr', aliases: ['Güceratça'], estimatedSpeakers: '57M' },
  { rank: 30, englishName: 'Bhojpuri', iso639_3: 'bho', nativeName: 'भोजपुरी', direction: 'ltr', aliases: [], estimatedSpeakers: '51M' },
  { rank: 31, englishName: 'Hausa', iso639_3: 'hau', nativeName: 'Hausa', direction: 'ltr', aliases: ['Hausaca'], estimatedSpeakers: '51M' },
  { rank: 32, englishName: 'Yoruba', iso639_3: 'yor', nativeName: 'Yorùbá', direction: 'ltr', aliases: ['Yorubaca'], estimatedSpeakers: '50M' },
  { rank: 33, englishName: 'Hakka Chinese', iso639_3: 'hak', nativeName: '客家话', direction: 'ltr', aliases: ['Hakka'], parentIso: 'zho', estimatedSpeakers: '48M' },
  { rank: 34, englishName: 'Indonesian', iso639_3: 'ind', nativeName: 'Bahasa Indonesia', direction: 'ltr', aliases: ['Endonezce'], estimatedSpeakers: '43M' },
  { rank: 35, englishName: 'Kannada', iso639_3: 'kan', nativeName: 'ಕನ್ನಡ', direction: 'ltr', aliases: ['Kannadaca'], estimatedSpeakers: '43M' },
  { rank: 36, englishName: 'Sundanese', iso639_3: 'sun', nativeName: 'Basa Sunda', direction: 'ltr', aliases: ['Sundaca'], estimatedSpeakers: '42M' },
  { rank: 37, englishName: 'Polish', iso639_3: 'pol', nativeName: 'Polski', direction: 'ltr', aliases: ['Lehçe', 'Polonyaca'], estimatedSpeakers: '40M' },
  { rank: 38, englishName: 'Malayalam', iso639_3: 'mal', nativeName: 'മലയാളം', direction: 'ltr', aliases: ['Malayalamca'], estimatedSpeakers: '38M' },
  { rank: 39, englishName: 'Xiang Chinese', iso639_3: 'hsn', nativeName: '湘语', direction: 'ltr', aliases: ['Hunanese'], parentIso: 'zho', estimatedSpeakers: '38M' },
  { rank: 40, englishName: 'Oromo', iso639_3: 'orm', nativeName: 'Afaan Oromoo', direction: 'ltr', aliases: ['Oromoca'], estimatedSpeakers: '37M' },
  { rank: 41, englishName: 'Algerian Arabic', iso639_3: 'arq', nativeName: 'الدارجة الجزائرية', direction: 'rtl', aliases: ['Darja', 'Cezayir Arapçası'], parentIso: 'ara', estimatedSpeakers: '35M' },
  { rank: 42, englishName: 'Odia', iso639_3: 'ory', nativeName: 'ଓଡ଼ିଆ', direction: 'ltr', aliases: ['Oriya'], estimatedSpeakers: '35M' },
  { rank: 43, englishName: 'Maithili', iso639_3: 'mai', nativeName: 'मैथिली', direction: 'ltr', aliases: [], estimatedSpeakers: '34M' },
  { rank: 44, englishName: 'Burmese', iso639_3: 'mya', nativeName: 'မြန်မာဘာသာ', direction: 'ltr', aliases: ['Birmanca', 'Myanmar'], estimatedSpeakers: '33M' },
  { rank: 45, englishName: 'Sudanese Arabic', iso639_3: 'apd', nativeName: 'العربية السودانية', direction: 'rtl', aliases: ['Sudan Arapçası'], parentIso: 'ara', estimatedSpeakers: '33M' },
  { rank: 46, englishName: 'Uzbek', iso639_3: 'uzb', nativeName: 'Oʻzbekcha', direction: 'ltr', aliases: ['Özbekçe', 'Uzbekcha'], estimatedSpeakers: '33M' },
  { rank: 47, englishName: 'Amharic', iso639_3: 'amh', nativeName: 'አማርኛ', direction: 'ltr', aliases: ['Amharca'], estimatedSpeakers: '32M' },
  { rank: 48, englishName: 'Sindhi', iso639_3: 'snd', nativeName: 'سنڌي', direction: 'rtl', aliases: ['Sintçe'], estimatedSpeakers: '32M' },
  { rank: 49, englishName: 'Nigerian Pidgin', iso639_3: 'pcm', nativeName: 'Naijá', direction: 'ltr', aliases: ['Naija', 'Pidgin English'], estimatedSpeakers: '30M' },
  { rank: 50, englishName: 'Filipino', iso639_3: 'fil', nativeName: 'Filipino', direction: 'ltr', aliases: ['Tagalog', 'Filipince'], estimatedSpeakers: '28M' },
  { rank: 51, englishName: 'Ukrainian', iso639_3: 'ukr', nativeName: 'Українська', direction: 'ltr', aliases: ['Ukraynaca'], estimatedSpeakers: '27M' },
  { rank: 52, englishName: 'Saraiki', iso639_3: 'skr', nativeName: 'سرائیکی', direction: 'rtl', aliases: ['Seraiki'], estimatedSpeakers: '26M' },
  { rank: 53, englishName: 'Dutch', iso639_3: 'nld', nativeName: 'Nederlands', direction: 'ltr', aliases: ['Hollandaca', 'Flemish'], estimatedSpeakers: '25M' },
  { rank: 54, englishName: 'Fula', iso639_3: 'ful', nativeName: 'Fulfulde', direction: 'ltr', aliases: ['Fulani', 'Pulaar'], estimatedSpeakers: '25M' },
  { rank: 55, englishName: 'Kurdish', iso639_3: 'kur', nativeName: 'Kurdî', direction: 'ltr', aliases: ['Kürtçe', 'Kurmanji'], estimatedSpeakers: '25M' },
  { rank: 56, englishName: 'Malagasy', iso639_3: 'mlg', nativeName: 'Malagasy', direction: 'ltr', aliases: ['Malgaşça'], estimatedSpeakers: '25M' },
  { rank: 57, englishName: 'Azerbaijani', iso639_3: 'aze', nativeName: 'Azərbaycan dili', direction: 'ltr', aliases: ['Azerice', 'Azeri'], estimatedSpeakers: '24M' },
  { rank: 58, englishName: 'Romanian', iso639_3: 'ron', nativeName: 'Română', direction: 'ltr', aliases: ['Rumence'], estimatedSpeakers: '24M' },
  { rank: 59, englishName: 'Cebuano', iso639_3: 'ceb', nativeName: 'Cebuano', direction: 'ltr', aliases: ['Bisaya'], estimatedSpeakers: '22M' },
  { rank: 60, englishName: 'Gan Chinese', iso639_3: 'gan', nativeName: '赣语', direction: 'ltr', aliases: ['Kan'], parentIso: 'zho', estimatedSpeakers: '22M' },
  { rank: 61, englishName: 'Somali', iso639_3: 'som', nativeName: 'Soomaali', direction: 'ltr', aliases: ['Somalice'], estimatedSpeakers: '22M' },
  { rank: 62, englishName: 'Lao', iso639_3: 'lao', nativeName: 'ພາສາລາວ', direction: 'ltr', aliases: ['Laosça'], estimatedSpeakers: '20M' },
  { rank: 63, englishName: 'Lingala', iso639_3: 'lin', nativeName: 'Lingála', direction: 'ltr', aliases: [], estimatedSpeakers: '20M' },
  { rank: 64, englishName: 'Swahili', iso639_3: 'swa', nativeName: 'Kiswahili', direction: 'ltr', aliases: ['Svahili', 'Suahili'], estimatedSpeakers: '20M' },
  { rank: 65, englishName: 'Mesopotamian Arabic', iso639_3: 'acm', nativeName: 'العربية العراقية', direction: 'rtl', aliases: ['Iraqi Arabic'], parentIso: 'ara', estimatedSpeakers: '19M' },
  { rank: 66, englishName: 'Saidi Arabic', iso639_3: 'aec', nativeName: 'العربية الصعيدية', direction: 'rtl', aliases: ['Upper Egyptian Arabic'], parentIso: 'ara', estimatedSpeakers: '19M' },
  { rank: 67, englishName: 'Chhattisgarhi', iso639_3: 'hne', nativeName: 'छत्तीसगढ़ी', direction: 'ltr', aliases: [], estimatedSpeakers: '18M' },
  { rank: 68, englishName: 'Rajasthani', iso639_3: 'raj', nativeName: 'राजस्थानी', direction: 'ltr', aliases: [], estimatedSpeakers: '18M' },
  { rank: 69, englishName: 'Hungarian', iso639_3: 'hun', nativeName: 'Magyar', direction: 'ltr', aliases: ['Macarca'], estimatedSpeakers: '17M' },
  { rank: 70, englishName: 'Dyula', iso639_3: 'dyu', nativeName: 'Julakan', direction: 'ltr', aliases: ['Jula', 'Dioula'], estimatedSpeakers: '16M' },
  { rank: 71, englishName: 'Khmer', iso639_3: 'khm', nativeName: 'ភាសាខ្មែរ', direction: 'ltr', aliases: ['Kamboçyaca', 'Cambodian'], estimatedSpeakers: '16M' },
  { rank: 72, englishName: 'Nepali', iso639_3: 'npi', nativeName: 'नेपाली', direction: 'ltr', aliases: ['Nepalce'], estimatedSpeakers: '16M' },
  { rank: 73, englishName: 'Sinhala', iso639_3: 'sin', nativeName: 'සිංහල', direction: 'ltr', aliases: ['Sinhalese', 'Seylanca'], estimatedSpeakers: '16M' },
  { rank: 74, englishName: 'Zhuang', iso639_3: 'zha', nativeName: 'Vahcuengh', direction: 'ltr', aliases: ['Çuangca'], estimatedSpeakers: '16M' },
  { rank: 75, englishName: 'Assamese', iso639_3: 'asm', nativeName: 'অসমীয়া', direction: 'ltr', aliases: ['Assamca'], estimatedSpeakers: '15M' },
  { rank: 76, englishName: 'Chittagonian', iso639_3: 'ctg', nativeName: 'চাটগাঁইয়া', direction: 'ltr', aliases: [], estimatedSpeakers: '15M' },
  { rank: 77, englishName: 'Kinyarwanda', iso639_3: 'kin', nativeName: 'Ikinyarwanda', direction: 'ltr', aliases: ['Rwanda'], estimatedSpeakers: '15M' },
  { rank: 78, englishName: 'North Levantine Arabic', iso639_3: 'apc', nativeName: 'العربية الشامية', direction: 'rtl', aliases: ['Levantine', 'Syrian Arabic'], parentIso: 'ara', estimatedSpeakers: '15M' },
  { rank: 79, englishName: 'Northeastern Thai', iso639_3: 'tts', nativeName: 'ภาษาอีสาน', direction: 'ltr', aliases: ['Isan'], estimatedSpeakers: '15M' },
  { rank: 80, englishName: 'Rangpuri', iso639_3: 'rkt', nativeName: 'রংপুরী', direction: 'ltr', aliases: [], estimatedSpeakers: '15M' },
  { rank: 81, englishName: 'Bambara', iso639_3: 'bam', nativeName: 'Bamanankan', direction: 'ltr', aliases: [], estimatedSpeakers: '14M' },
  { rank: 82, englishName: 'Bavarian', iso639_3: 'bar', nativeName: 'Boarisch', direction: 'ltr', aliases: ['Bairisch'], estimatedSpeakers: '14M' },
  { rank: 83, englishName: 'Pedi', iso639_3: 'nso', nativeName: 'Sepedi', direction: 'ltr', aliases: ['Northern Sotho'], estimatedSpeakers: '14M' },
  { rank: 84, englishName: 'Southern Sotho', iso639_3: 'sot', nativeName: 'Sesotho', direction: 'ltr', aliases: ['Sotho'], estimatedSpeakers: '14M' },
  { rank: 85, englishName: 'Akan', iso639_3: 'aka', nativeName: 'Akan', direction: 'ltr', aliases: ['Twi', 'Fante'], estimatedSpeakers: '13M' },
  { rank: 86, englishName: 'Deccan', iso639_3: 'dcc', nativeName: 'دکنی', direction: 'ltr', aliases: ['Deccani'], estimatedSpeakers: '13M' },
  { rank: 87, englishName: 'Haryanvi', iso639_3: 'bgc', nativeName: 'हरियाणवी', direction: 'ltr', aliases: [], estimatedSpeakers: '13M' },
  { rank: 88, englishName: 'Kazakh', iso639_3: 'kaz', nativeName: 'Қазақ тілі', direction: 'ltr', aliases: ['Kazakça'], estimatedSpeakers: '13M' },
  { rank: 89, englishName: 'Magahi', iso639_3: 'mag', nativeName: 'मगही', direction: 'ltr', aliases: [], estimatedSpeakers: '13M' },
  { rank: 90, englishName: 'Modern Greek', iso639_3: 'ell', nativeName: 'Ελληνικά', direction: 'ltr', aliases: ['Yunanca', 'Greek'], estimatedSpeakers: '13M' },
  { rank: 91, englishName: 'Pashto', iso639_3: 'pus', nativeName: 'پښتو', direction: 'rtl', aliases: ['Peştuca', 'Pushto'], estimatedSpeakers: '13M' },
  { rank: 92, englishName: 'Tsonga', iso639_3: 'tso', nativeName: 'Xitsonga', direction: 'ltr', aliases: [], estimatedSpeakers: '13M' },
  { rank: 93, englishName: 'Dagbani', iso639_3: 'dag', nativeName: 'Dagbanli', direction: 'ltr', aliases: [], estimatedSpeakers: '12M' },
  { rank: 94, englishName: 'Haitian Creole', iso639_3: 'hat', nativeName: 'Kreyòl ayisyen', direction: 'ltr', aliases: ['Haitian'], estimatedSpeakers: '12M' },
  { rank: 95, englishName: 'Nyanja', iso639_3: 'nya', nativeName: 'Chichewa', direction: 'ltr', aliases: ['Chewa'], estimatedSpeakers: '12M' },
  { rank: 96, englishName: 'Serbian', iso639_3: 'srp', nativeName: 'Српски', direction: 'ltr', aliases: ['Sırpça'], estimatedSpeakers: '12M' },
  { rank: 97, englishName: 'Zulu', iso639_3: 'zul', nativeName: 'isiZulu', direction: 'ltr', aliases: ['Zuluca'], estimatedSpeakers: '12M' },
  { rank: 98, englishName: 'Gulf Arabic', iso639_3: 'afb', nativeName: 'العربية الخليجية', direction: 'rtl', aliases: ['Khaliji', 'Körfez Arapçası'], parentIso: 'ara', estimatedSpeakers: '11M' },
  { rank: 99, englishName: 'Hijazi Arabic', iso639_3: 'acw', nativeName: 'العربية الحجازية', direction: 'rtl', aliases: ['Hejazi'], parentIso: 'ara', estimatedSpeakers: '11M' },
  { rank: 100, englishName: 'Rundi', iso639_3: 'run', nativeName: 'Ikirundi', direction: 'ltr', aliases: ['Kirundi'], estimatedSpeakers: '11M' },
  // 101-150
  { rank: 101, englishName: 'Tunisian Arabic', iso639_3: 'aeb', nativeName: 'العربية التونسية', direction: 'rtl', aliases: ['Derja'], parentIso: 'ara', estimatedSpeakers: '11M' },
  { rank: 102, englishName: 'Turkmen', iso639_3: 'tuk', nativeName: 'Türkmençe', direction: 'ltr', aliases: ['Türkmence'], estimatedSpeakers: '11M' },
  { rank: 103, englishName: 'Czech', iso639_3: 'ces', nativeName: 'Čeština', direction: 'ltr', aliases: ['Çekçe'], estimatedSpeakers: '10M' },
  { rank: 104, englishName: 'Dhundari', iso639_3: 'dhd', nativeName: 'ढूँढाड़ी', direction: 'ltr', aliases: [], estimatedSpeakers: '10M' },
  { rank: 105, englishName: 'Kanauji', iso639_3: 'bjj', nativeName: 'कनौजी', direction: 'ltr', aliases: [], estimatedSpeakers: '10M' },
  { rank: 106, englishName: 'Mainfränkisch', iso639_3: 'vmf', nativeName: 'Mainfränkisch', direction: 'ltr', aliases: ['East Franconian'], estimatedSpeakers: '10M' },
  { rank: 107, englishName: 'Min Bei Chinese', iso639_3: 'mnp', nativeName: '闽北语', direction: 'ltr', aliases: [], parentIso: 'zho', estimatedSpeakers: '10M' },
  { rank: 108, englishName: 'Min Dong Chinese', iso639_3: 'cdo', nativeName: '闽东语', direction: 'ltr', aliases: ['Fuzhounese'], parentIso: 'zho', estimatedSpeakers: '10M' },
  { rank: 109, englishName: 'North Mesopotamian Arabic', iso639_3: 'ayp', nativeName: 'العربية الموصلية', direction: 'rtl', aliases: ['Moslawi'], parentIso: 'ara', estimatedSpeakers: '10M' },
  { rank: 110, englishName: 'Swedish', iso639_3: 'swe', nativeName: 'Svenska', direction: 'ltr', aliases: ['İsveççe'], estimatedSpeakers: '10M' },
  { rank: 111, englishName: 'Sylheti', iso639_3: 'syl', nativeName: 'ꠍꠤꠟꠐꠤ', direction: 'ltr', aliases: [], estimatedSpeakers: '10M' },
  { rank: 112, englishName: 'Uyghur', iso639_3: 'uig', nativeName: 'ئۇيغۇرچە', direction: 'rtl', aliases: ['Uygurca', 'Uighur'], estimatedSpeakers: '10M' },
  { rank: 113, englishName: 'Xhosa', iso639_3: 'xho', nativeName: 'isiXhosa', direction: 'ltr', aliases: [], estimatedSpeakers: '10M' },
  { rank: 114, englishName: 'Bosnian', iso639_3: 'bos', nativeName: 'Bosanski', direction: 'ltr', aliases: ['Boşnakça'], estimatedSpeakers: '9M' },
  { rank: 115, englishName: 'Eastern Oromo', iso639_3: 'hae', nativeName: 'Afaan Oromoo', direction: 'ltr', aliases: ['Harar Oromo'], estimatedSpeakers: '9M' },
  { rank: 116, englishName: 'Ilocano', iso639_3: 'ilo', nativeName: 'Ilokano', direction: 'ltr', aliases: ['Iloko'], estimatedSpeakers: '9M' },
  { rank: 117, englishName: 'Kalenjin', iso639_3: 'kln', nativeName: 'Kalenjin', direction: 'ltr', aliases: [], estimatedSpeakers: '9M' },
  { rank: 118, englishName: 'Maay', iso639_3: 'ymm', nativeName: 'Af-Maay', direction: 'ltr', aliases: [], estimatedSpeakers: '9M' },
  { rank: 119, englishName: 'Quechua', iso639_3: 'que', nativeName: 'Runasimi', direction: 'ltr', aliases: ['Keçuva'], estimatedSpeakers: '9M' },
  { rank: 120, englishName: 'Shona', iso639_3: 'sna', nativeName: 'chiShona', direction: 'ltr', aliases: [], estimatedSpeakers: '9M' },
  { rank: 121, englishName: 'Tigrinya', iso639_3: 'tir', nativeName: 'ትግርኛ', direction: 'ltr', aliases: ['Tigrinya'], estimatedSpeakers: '9M' },
  { rank: 122, englishName: 'Bagheli', iso639_3: 'bfy', nativeName: 'बघेली', direction: 'ltr', aliases: [], estimatedSpeakers: '8M' },
  { rank: 123, englishName: 'Baluchi', iso639_3: 'bal', nativeName: 'بلوچی', direction: 'rtl', aliases: ['Belucice', 'Balochi'], estimatedSpeakers: '8M' },
  { rank: 124, englishName: 'Kanuri', iso639_3: 'kau', nativeName: 'Kanuri', direction: 'ltr', aliases: [], estimatedSpeakers: '8M' },
  { rank: 125, englishName: 'Kyrgyz', iso639_3: 'kir', nativeName: 'Кыргызча', direction: 'ltr', aliases: ['Kırgızca'], estimatedSpeakers: '8M' },
  { rank: 126, englishName: 'Marwari', iso639_3: 'mwr', nativeName: 'मारवाड़ी', direction: 'ltr', aliases: [], estimatedSpeakers: '8M' },
  { rank: 127, englishName: 'Marwari (India)', iso639_3: 'rwr', nativeName: 'मारवाड़ी', direction: 'ltr', aliases: [], estimatedSpeakers: '8M' },
  { rank: 128, englishName: 'Merwari', iso639_3: 'wry', nativeName: 'मेवाड़ी', direction: 'ltr', aliases: [], estimatedSpeakers: '8M' },
  { rank: 129, englishName: 'Sukuma', iso639_3: 'suk', nativeName: 'Sukuma', direction: 'ltr', aliases: [], estimatedSpeakers: '8M' },
  { rank: 130, englishName: 'Tajik', iso639_3: 'tgk', nativeName: 'Тоҷикӣ', direction: 'ltr', aliases: ['Tacikçe'], estimatedSpeakers: '8M' },
  { rank: 131, englishName: 'Tswana', iso639_3: 'tsn', nativeName: 'Setswana', direction: 'ltr', aliases: [], estimatedSpeakers: '8M' },
  { rank: 132, englishName: 'Afrikaans', iso639_3: 'afr', nativeName: 'Afrikaans', direction: 'ltr', aliases: ['Afrikaanca'], estimatedSpeakers: '7M' },
  { rank: 133, englishName: 'Banjar', iso639_3: 'bjn', nativeName: 'Bahasa Banjar', direction: 'ltr', aliases: [], estimatedSpeakers: '7M' },
  { rank: 134, englishName: 'Bulgarian', iso639_3: 'bul', nativeName: 'Български', direction: 'ltr', aliases: ['Bulgarca'], estimatedSpeakers: '7M' },
  { rank: 135, englishName: 'Central Kurdish', iso639_3: 'ckb', nativeName: 'کوردیی ناوەندی', direction: 'rtl', aliases: ['Sorani', 'Soranice'], parentIso: 'kur', estimatedSpeakers: '7M' },
  { rank: 136, englishName: 'Hiligaynon', iso639_3: 'hil', nativeName: 'Hiligaynon', direction: 'ltr', aliases: ['Ilonggo'], estimatedSpeakers: '7M' },
  { rank: 137, englishName: 'Kashmiri', iso639_3: 'kas', nativeName: 'كٲشُر', direction: 'rtl', aliases: ['Keşmirce'], estimatedSpeakers: '7M' },
  { rank: 138, englishName: 'Kikuyu', iso639_3: 'kik', nativeName: 'Gĩkũyũ', direction: 'ltr', aliases: ['Gikuyu'], estimatedSpeakers: '7M' },
  { rank: 139, englishName: 'Madurese', iso639_3: 'mad', nativeName: 'Basa Madura', direction: 'ltr', aliases: [], estimatedSpeakers: '7M' },
  { rank: 140, englishName: 'Makhuwa', iso639_3: 'vmw', nativeName: 'Emakhuwa', direction: 'ltr', aliases: [], estimatedSpeakers: '7M' },
  { rank: 141, englishName: 'Makhuwa-Meetto', iso639_3: 'mgh', nativeName: 'Emakhuwa', direction: 'ltr', aliases: [], estimatedSpeakers: '7M' },
  { rank: 142, englishName: 'Mossi', iso639_3: 'mos', nativeName: 'Mooré', direction: 'ltr', aliases: ['Mòoré'], estimatedSpeakers: '7M' },
  { rank: 143, englishName: 'Santali', iso639_3: 'sat', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ', direction: 'ltr', aliases: [], estimatedSpeakers: '7M' },
  { rank: 144, englishName: "Ta'izzi-Adeni Arabic", iso639_3: 'acq', nativeName: 'العربية التعزية', direction: 'rtl', aliases: ['Yemeni Arabic'], parentIso: 'ara', estimatedSpeakers: '7M' },
  { rank: 145, englishName: 'Umbundu', iso639_3: 'umb', nativeName: 'Umbundu', direction: 'ltr', aliases: [], estimatedSpeakers: '7M' },
  { rank: 146, englishName: 'Varhadi-Nagpuri', iso639_3: 'vah', nativeName: 'वऱ्हाडी', direction: 'ltr', aliases: [], estimatedSpeakers: '7M' },
  { rank: 147, englishName: 'Wolaytta', iso639_3: 'wal', nativeName: 'Wolaytta', direction: 'ltr', aliases: [], estimatedSpeakers: '7M' },
  { rank: 148, englishName: 'Albanian', iso639_3: 'sqi', nativeName: 'Shqip', direction: 'ltr', aliases: ['Arnavutça'], estimatedSpeakers: '6M' },
  { rank: 149, englishName: 'Armenian', iso639_3: 'hye', nativeName: 'Հայերեն', direction: 'ltr', aliases: ['Ermenice'], estimatedSpeakers: '6M' },
  { rank: 150, englishName: 'Kabyle', iso639_3: 'kab', nativeName: 'Taqbaylit', direction: 'ltr', aliases: ['Kabilce'], estimatedSpeakers: '6M' },
  // 151-200
  { rank: 151, englishName: 'Kongo', iso639_3: 'kon', nativeName: 'Kikongo', direction: 'ltr', aliases: [], estimatedSpeakers: '6M' },
  { rank: 152, englishName: 'Lambadi', iso639_3: 'lmn', nativeName: 'लम्बाडी', direction: 'ltr', aliases: ['Banjara'], estimatedSpeakers: '6M' },
  { rank: 153, englishName: 'Luba-Lulua', iso639_3: 'lua', nativeName: 'Tshiluba', direction: 'ltr', aliases: [], estimatedSpeakers: '6M' },
  { rank: 154, englishName: 'Mazanderani', iso639_3: 'mzn', nativeName: 'مازرونی', direction: 'rtl', aliases: ['Tabari'], estimatedSpeakers: '6M' },
  { rank: 155, englishName: 'Minangkabau', iso639_3: 'min', nativeName: 'Baso Minangkabau', direction: 'ltr', aliases: [], estimatedSpeakers: '6M' },
  { rank: 156, englishName: 'Neapolitan', iso639_3: 'nap', nativeName: 'Napoletano', direction: 'ltr', aliases: [], estimatedSpeakers: '6M' },
  { rank: 157, englishName: 'Northern Thai', iso639_3: 'nod', nativeName: 'ภาษาเหนือ', direction: 'ltr', aliases: ['Lanna'], estimatedSpeakers: '6M' },
  { rank: 158, englishName: 'Belarusian', iso639_3: 'bel', nativeName: 'Беларуская', direction: 'ltr', aliases: ['Belarusça'], estimatedSpeakers: '5M' },
  { rank: 159, englishName: 'Betawi', iso639_3: 'bew', nativeName: 'Bahasa Betawi', direction: 'ltr', aliases: [], estimatedSpeakers: '5M' },
  { rank: 160, englishName: 'Buginese', iso639_3: 'bug', nativeName: 'ᨅᨔ ᨕᨘᨁᨗ', direction: 'ltr', aliases: ['Bugis'], estimatedSpeakers: '5M' },
  { rank: 161, englishName: 'Danish', iso639_3: 'dan', nativeName: 'Dansk', direction: 'ltr', aliases: ['Danca'], estimatedSpeakers: '5M' },
  { rank: 162, englishName: 'Finnish', iso639_3: 'fin', nativeName: 'Suomi', direction: 'ltr', aliases: ['Fince'], estimatedSpeakers: '5M' },
  { rank: 163, englishName: 'Ghanaian Pidgin English', iso639_3: 'gpe', nativeName: 'Ghanaian Pidgin', direction: 'ltr', aliases: [], estimatedSpeakers: '5M' },
  { rank: 164, englishName: 'Guarani', iso639_3: 'grn', nativeName: "Avañe'ẽ", direction: 'ltr', aliases: [], estimatedSpeakers: '5M' },
  { rank: 165, englishName: 'Hadothi', iso639_3: 'hoj', nativeName: 'हाड़ौती', direction: 'ltr', aliases: [], estimatedSpeakers: '5M' },
  { rank: 166, englishName: 'Huizhou Chinese', iso639_3: 'czh', nativeName: '徽语', direction: 'ltr', aliases: [], parentIso: 'zho', estimatedSpeakers: '5M' },
  { rank: 167, englishName: 'Kituba (Congo)', iso639_3: 'mkw', nativeName: 'Kituba', direction: 'ltr', aliases: [], estimatedSpeakers: '5M' },
  { rank: 168, englishName: 'Kituba (DRC)', iso639_3: 'ktu', nativeName: 'Kituba', direction: 'ltr', aliases: [], estimatedSpeakers: '5M' },
  { rank: 169, englishName: 'Libyan Arabic', iso639_3: 'ayl', nativeName: 'العربية الليبية', direction: 'rtl', aliases: ['Libya Arapçası'], parentIso: 'ara', estimatedSpeakers: '5M' },
  { rank: 170, englishName: 'Makasar', iso639_3: 'mak', nativeName: 'Basa Mangkasara', direction: 'ltr', aliases: ['Makassarese'], estimatedSpeakers: '5M' },
  { rank: 171, englishName: 'Malvi', iso639_3: 'mup', nativeName: 'माळवी', direction: 'ltr', aliases: [], estimatedSpeakers: '5M' },
  { rank: 172, englishName: 'Mewari', iso639_3: 'mtr', nativeName: 'मेवाड़ी', direction: 'ltr', aliases: [], estimatedSpeakers: '5M' },
  { rank: 173, englishName: 'Mongolian', iso639_3: 'mon', nativeName: 'Монгол хэл', direction: 'ltr', aliases: ['Moğolca'], estimatedSpeakers: '5M' },
  { rank: 174, englishName: 'Norwegian', iso639_3: 'nor', nativeName: 'Norsk', direction: 'ltr', aliases: ['Norveççe'], estimatedSpeakers: '5M' },
  { rank: 175, englishName: 'Slovak', iso639_3: 'slk', nativeName: 'Slovenčina', direction: 'ltr', aliases: ['Slovakça'], estimatedSpeakers: '5M' },
  { rank: 176, englishName: 'Swiss German', iso639_3: 'gsw', nativeName: 'Schwyzerdütsch', direction: 'ltr', aliases: [], estimatedSpeakers: '5M' },
  { rank: 177, englishName: 'Tachelhit', iso639_3: 'shi', nativeName: 'ⵜⴰⵛⵍⵃⵉⵜ', direction: 'ltr', aliases: ['Shilha'], estimatedSpeakers: '5M' },
  { rank: 178, englishName: 'Tiv', iso639_3: 'tiv', nativeName: 'Tiv', direction: 'ltr', aliases: [], estimatedSpeakers: '5M' },
  { rank: 179, englishName: 'Achinese', iso639_3: 'ace', nativeName: 'Bahsa Acèh', direction: 'ltr', aliases: ['Acehnese'], estimatedSpeakers: '4M' },
  { rank: 180, englishName: 'Awadhi', iso639_3: 'awa', nativeName: 'अवधी', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 181, englishName: 'Bangala', iso639_3: 'bxg', nativeName: 'Bangala', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 182, englishName: 'Baoulé', iso639_3: 'bci', nativeName: 'Baoulé', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 183, englishName: 'Bemba (Zambia)', iso639_3: 'bem', nativeName: 'Chibemba', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 184, englishName: 'Catalan', iso639_3: 'cat', nativeName: 'Català', direction: 'ltr', aliases: ['Katalanca'], estimatedSpeakers: '4M' },
  { rank: 185, englishName: 'Croatian', iso639_3: 'hrv', nativeName: 'Hrvatski', direction: 'ltr', aliases: ['Hırvatça'], estimatedSpeakers: '4M' },
  { rank: 186, englishName: 'Ewe', iso639_3: 'ewe', nativeName: 'Eʋegbe', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 187, englishName: 'Ganda', iso639_3: 'lug', nativeName: 'Luganda', direction: 'ltr', aliases: ['Luganda'], estimatedSpeakers: '4M' },
  { rank: 188, englishName: 'Georgian', iso639_3: 'kat', nativeName: 'ქართული', direction: 'ltr', aliases: ['Gürcüce'], estimatedSpeakers: '4M' },
  { rank: 189, englishName: 'Modern Hebrew', iso639_3: 'heb', nativeName: 'עברית', direction: 'rtl', aliases: ['İbranice', 'Hebrew'], estimatedSpeakers: '4M' },
  { rank: 190, englishName: 'Kamba (Kenya)', iso639_3: 'kam', nativeName: 'Kĩkamba', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 191, englishName: 'Kimbundu', iso639_3: 'kmb', nativeName: 'Kimbundu', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 192, englishName: 'Konkani', iso639_3: 'kok', nativeName: 'कोंकणी', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 193, englishName: 'Krio', iso639_3: 'kri', nativeName: 'Krio', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 194, englishName: 'Lombard', iso639_3: 'lmo', nativeName: 'Lombard', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 195, englishName: 'Luo (Kenya)', iso639_3: 'luo', nativeName: 'Dholuo', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 196, englishName: 'Makhuwa-Shirima', iso639_3: 'vmk', nativeName: 'Emakhuwa', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 197, englishName: 'Northern Hindko', iso639_3: 'hno', nativeName: 'ہندکو', direction: 'ltr', aliases: ['Hindko'], estimatedSpeakers: '4M' },
  { rank: 198, englishName: 'Romany', iso639_3: 'rom', nativeName: 'Romani', direction: 'ltr', aliases: ['Romani', 'Romanca'], estimatedSpeakers: '4M' },
  { rank: 199, englishName: 'Sadri', iso639_3: 'sck', nativeName: 'सादरी', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 200, englishName: 'Shan', iso639_3: 'shn', nativeName: 'လိၵ်ႈတႆး', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  // 201-250
  { rank: 201, englishName: 'Sicilian', iso639_3: 'scn', nativeName: 'Sicilianu', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 202, englishName: 'Sidamo', iso639_3: 'sid', nativeName: 'Sidaamu Afoo', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 203, englishName: 'Southern Thai', iso639_3: 'sou', nativeName: 'ภาษาใต้', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 204, englishName: 'Takwane', iso639_3: 'tke', nativeName: 'Takwane', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 205, englishName: 'Tatar', iso639_3: 'tat', nativeName: 'Татарча', direction: 'ltr', aliases: ['Tatarca'], estimatedSpeakers: '4M' },
  { rank: 206, englishName: 'Tok Pisin', iso639_3: 'tpi', nativeName: 'Tok Pisin', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 207, englishName: 'Venetian', iso639_3: 'vec', nativeName: 'Vèneto', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 208, englishName: 'Wolof', iso639_3: 'wol', nativeName: 'Wolof', direction: 'ltr', aliases: [], estimatedSpeakers: '4M' },
  { rank: 209, englishName: 'Zarma', iso639_3: 'dje', nativeName: 'Zarma', direction: 'ltr', aliases: ['Djerma'], estimatedSpeakers: '4M' },
  { rank: 210, englishName: 'Aymara', iso639_3: 'aym', nativeName: 'Aymar aru', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 211, englishName: 'Balinese', iso639_3: 'ban', nativeName: 'Basa Bali', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 212, englishName: 'Bhili', iso639_3: 'bhb', nativeName: 'भीली', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 213, englishName: 'Bouyei', iso639_3: 'pcc', nativeName: 'Haausqyaix', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 214, englishName: 'Brahui', iso639_3: 'brh', nativeName: 'براہوئی', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 215, englishName: 'Bundeli', iso639_3: 'bns', nativeName: 'बुन्देली', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 216, englishName: 'Cebaara Senoufo', iso639_3: 'sef', nativeName: 'Cebaara', direction: 'ltr', aliases: ['Senoufo'], estimatedSpeakers: '3M' },
  { rank: 217, englishName: 'Emilian', iso639_3: 'egl', nativeName: 'Emiliàn', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 218, englishName: 'Garhwali', iso639_3: 'gbm', nativeName: 'गढ़वाळी', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 219, englishName: 'Godwari', iso639_3: 'gdx', nativeName: 'गोदवारी', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 220, englishName: 'Gondi', iso639_3: 'gon', nativeName: 'గొండి', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 221, englishName: 'Hassaniyya', iso639_3: 'mey', nativeName: 'الحسانية', direction: 'rtl', aliases: ['Hassaniya Arabic'], parentIso: 'ara', estimatedSpeakers: '3M' },
  { rank: 222, englishName: 'Hazaragi', iso639_3: 'haz', nativeName: 'هزارگی', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 223, englishName: 'Hmong', iso639_3: 'hmn', nativeName: 'Hmoob', direction: 'ltr', aliases: ['Mong'], estimatedSpeakers: '3M' },
  { rank: 224, englishName: 'Hunsrik', iso639_3: 'hrx', nativeName: 'Hunsrik', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 225, englishName: 'Jamaican Creole English', iso639_3: 'jam', nativeName: 'Patois', direction: 'ltr', aliases: ['Jamaican Patois'], estimatedSpeakers: '3M' },
  { rank: 226, englishName: 'Kedah Malay', iso639_3: 'meo', nativeName: 'Bahasa Kedah', direction: 'ltr', aliases: [], parentIso: 'msa', estimatedSpeakers: '3M' },
  { rank: 227, englishName: 'Lithuanian', iso639_3: 'lit', nativeName: 'Lietuvių', direction: 'ltr', aliases: ['Litvanca'], estimatedSpeakers: '3M' },
  { rank: 228, englishName: 'Masaaba', iso639_3: 'myx', nativeName: 'Lumasaaba', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 229, englishName: 'Mende (Sierra Leone)', iso639_3: 'men', nativeName: 'Mɛnde', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 230, englishName: 'Mewati', iso639_3: 'wtm', nativeName: 'मेवाती', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 231, englishName: 'Musi', iso639_3: 'mui', nativeName: 'Baso Musi', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 232, englishName: 'Northern Gondi', iso639_3: 'gno', nativeName: 'गोंडी', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 233, englishName: 'Nyankole', iso639_3: 'nyn', nativeName: 'Runyankole', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 234, englishName: 'Pu-Xian Chinese', iso639_3: 'cpx', nativeName: '莆仙话', direction: 'ltr', aliases: [], parentIso: 'zho', estimatedSpeakers: '3M' },
  { rank: 235, englishName: "S'gaw Karen", iso639_3: 'ksw', nativeName: 'စှီၤကျိာ်', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 236, englishName: 'Sabah Malay', iso639_3: 'msi', nativeName: 'Bahasa Melayu Sabah', direction: 'ltr', aliases: [], parentIso: 'msa', estimatedSpeakers: '3M' },
  { rank: 237, englishName: 'Shekhawati', iso639_3: 'swv', nativeName: 'शेखावाटी', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 238, englishName: 'Soga', iso639_3: 'xog', nativeName: 'Lusoga', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 239, englishName: 'South Bolivian Quechua', iso639_3: 'quh', nativeName: 'Qhichwa', direction: 'ltr', aliases: [], parentIso: 'que', estimatedSpeakers: '3M' },
  { rank: 240, englishName: 'Southern Kurdish', iso639_3: 'sdh', nativeName: 'کوردی خوارین', direction: 'rtl', aliases: [], parentIso: 'kur', estimatedSpeakers: '3M' },
  { rank: 241, englishName: 'Swazi', iso639_3: 'ssw', nativeName: 'siSwati', direction: 'ltr', aliases: ['Swati'], estimatedSpeakers: '3M' },
  { rank: 242, englishName: 'Tày', iso639_3: 'tyz', nativeName: 'Tày', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 243, englishName: 'Wagdi', iso639_3: 'wbr', nativeName: 'वागड़ी', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 244, englishName: 'Waray (Philippines)', iso639_3: 'war', nativeName: 'Winaray', direction: 'ltr', aliases: ['Waray-Waray'], estimatedSpeakers: '3M' },
  { rank: 245, englishName: 'Yao', iso639_3: 'yao', nativeName: 'Chiyao', direction: 'ltr', aliases: [], estimatedSpeakers: '3M' },
  { rank: 246, englishName: 'Zaza', iso639_3: 'zza', nativeName: 'Zazakî', direction: 'ltr', aliases: ['Zazaca', 'Dimli', 'Kirmanjki'], estimatedSpeakers: '3M' },
  { rank: 247, englishName: 'Afar', iso639_3: 'aar', nativeName: 'Qafar af', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 248, englishName: 'Alur', iso639_3: 'alz', nativeName: 'Dhu Alur', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 249, englishName: 'Ambonese Malay', iso639_3: 'abs', nativeName: 'Bahasa Melayu Ambon', direction: 'ltr', aliases: [], parentIso: 'msa', estimatedSpeakers: '2M' },
  { rank: 250, englishName: 'Anaang', iso639_3: 'anw', nativeName: 'Anaang', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  // 251-300
  { rank: 251, englishName: 'Bagri', iso639_3: 'bgq', nativeName: 'बागड़ी', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 252, englishName: 'Batak Toba', iso639_3: 'bbc', nativeName: 'Hata Batak Toba', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 253, englishName: 'Bikol', iso639_3: 'bik', nativeName: 'Bikol', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 254, englishName: 'Bini', iso639_3: 'bin', nativeName: 'Ẹ̀dó', direction: 'ltr', aliases: ['Edo'], estimatedSpeakers: '2M' },
  { rank: 255, englishName: 'Braj', iso639_3: 'bra', nativeName: 'ब्रज भाषा', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 256, englishName: 'Cameroon Pidgin', iso639_3: 'wes', nativeName: 'Kamtok', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 257, englishName: 'Central Atlas Tamazight', iso639_3: 'tzm', nativeName: 'ⵜⴰⵎⴰⵣⵉⵖⵜ', direction: 'ltr', aliases: ['Berber', 'Tamazight'], estimatedSpeakers: '2M' },
  { rank: 258, englishName: 'Central Bikol', iso639_3: 'bcl', nativeName: 'Bikol Sentral', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 259, englishName: 'Central Malay', iso639_3: 'pse', nativeName: 'Bahasa Melayu', direction: 'ltr', aliases: [], parentIso: 'msa', estimatedSpeakers: '2M' },
  { rank: 260, englishName: 'Central Okinawan', iso639_3: 'ryu', nativeName: 'うちなーぐち', direction: 'ltr', aliases: ['Okinawan'], estimatedSpeakers: '2M' },
  { rank: 261, englishName: 'Chadian Arabic', iso639_3: 'shu', nativeName: 'العربية التشادية', direction: 'rtl', aliases: ['Çad Arapçası'], parentIso: 'ara', estimatedSpeakers: '2M' },
  { rank: 262, englishName: 'Chiga', iso639_3: 'cgg', nativeName: 'Rukiga', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 263, englishName: 'Dan', iso639_3: 'dnj', nativeName: 'Dan', direction: 'ltr', aliases: ['Yakuba'], estimatedSpeakers: '2M' },
  { rank: 264, englishName: 'Dangaura Tharu', iso639_3: 'thl', nativeName: 'थारु', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 265, englishName: 'Dogri', iso639_3: 'doi', nativeName: 'डोगरी', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 266, englishName: 'Eastern Balochi', iso639_3: 'bgp', nativeName: 'بلوچی', direction: 'rtl', aliases: [], estimatedSpeakers: '2M' },
  { rank: 267, englishName: 'Ebira', iso639_3: 'igb', nativeName: 'Ebira', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 268, englishName: 'Efik', iso639_3: 'efi', nativeName: 'Efịk', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 269, englishName: 'Fon', iso639_3: 'fon', nativeName: 'Fɔ̀ngbè', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 270, englishName: 'Galician', iso639_3: 'glg', nativeName: 'Galego', direction: 'ltr', aliases: ['Galiçyaca'], estimatedSpeakers: '2M' },
  { rank: 271, englishName: 'Gamo', iso639_3: 'gmv', nativeName: 'Gamo', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 272, englishName: 'Gilaki', iso639_3: 'glk', nativeName: 'گیلکی', direction: 'rtl', aliases: [], estimatedSpeakers: '2M' },
  { rank: 273, englishName: 'Giryama', iso639_3: 'nyf', nativeName: 'Kigiriama', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 274, englishName: 'Goan Konkani', iso639_3: 'gom', nativeName: 'कोंकणी', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 275, englishName: 'Gusii', iso639_3: 'guz', nativeName: 'Ekegusii', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 276, englishName: 'Hmong Daw', iso639_3: 'mww', nativeName: 'Hmoob Dawb', direction: 'ltr', aliases: ['White Hmong'], estimatedSpeakers: '2M' },
  { rank: 277, englishName: 'Iban', iso639_3: 'iba', nativeName: 'Jaku Iban', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 278, englishName: 'Ibibio', iso639_3: 'ibb', nativeName: 'Ibibio', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 279, englishName: 'Izon', iso639_3: 'ijc', nativeName: 'Ịzọn', direction: 'ltr', aliases: ['Ijaw'], estimatedSpeakers: '2M' },
  { rank: 280, englishName: "K'iche'", iso639_3: 'quc', nativeName: "K'iche'", direction: 'ltr', aliases: ['Quiché'], estimatedSpeakers: '2M' },
  { rank: 281, englishName: 'Kabardian', iso639_3: 'kbd', nativeName: 'Адыгэбзэ', direction: 'ltr', aliases: ['Circassian'], estimatedSpeakers: '2M' },
  { rank: 282, englishName: 'Kangri', iso639_3: 'xnr', nativeName: 'कांगड़ी', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 283, englishName: 'Khandesi', iso639_3: 'khn', nativeName: 'खान्देशी', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 284, englishName: 'Kipsigis', iso639_3: 'sgc', nativeName: 'Kipsigis', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 285, englishName: 'Kumaoni', iso639_3: 'kfy', nativeName: 'कुमाऊँनी', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 286, englishName: 'Kurukh', iso639_3: 'kru', nativeName: 'कुड़ुख़', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 287, englishName: 'Lampung Nyo', iso639_3: 'abl', nativeName: 'Bahasa Lampung', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 288, englishName: 'Lango (Uganda)', iso639_3: 'laj', nativeName: 'Lëb Laŋo', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 289, englishName: 'Liberian English', iso639_3: 'lir', nativeName: 'Liberian English', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 290, englishName: 'Lisu', iso639_3: 'lis', nativeName: 'ꓡꓲꓢꓴ', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 291, englishName: 'Lomwe', iso639_3: 'ngl', nativeName: 'Elomwe', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 292, englishName: 'Luba-Katanga', iso639_3: 'lub', nativeName: 'Kiluba', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 293, englishName: 'Lugbara', iso639_3: 'lgg', nativeName: 'Lugbara', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 294, englishName: 'Makassar Malay', iso639_3: 'mfp', nativeName: 'Bahasa Melayu Makassar', direction: 'ltr', aliases: [], parentIso: 'msa', estimatedSpeakers: '2M' },
  { rank: 295, englishName: 'Malawi Lomwe', iso639_3: 'lon', nativeName: 'Elomwe', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 296, englishName: 'Mandeali', iso639_3: 'mjl', nativeName: 'मण्डेआली', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 297, englishName: 'Meitei', iso639_3: 'mni', nativeName: 'মৈতৈলোন্', direction: 'ltr', aliases: ['Manipuri'], estimatedSpeakers: '2M' },
  { rank: 298, englishName: 'Meru', iso639_3: 'mer', nativeName: 'Kĩmĩrũ', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 299, englishName: 'Mundari', iso639_3: 'unr', nativeName: 'मुंडारी', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
  { rank: 300, englishName: 'Ndau', iso639_3: 'ndc', nativeName: 'chiNdau', direction: 'ltr', aliases: [], estimatedSpeakers: '2M' },
];

// Virtual parent languages (macrolanguage entries for grouping)
export const QA_PARENT_LANGUAGES: Qa300LanguageEntry[] = [
  { rank: 0, englishName: 'Chinese', iso639_3: 'zho', nativeName: '中文', direction: 'ltr', aliases: ['Çince', 'Zhongwen'], estimatedSpeakers: '1400M' },
];
